#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

//#define STATIC_TEXTURE 0
//#define DYNAMIC_TEXTURE 1

#define WALL 1

#define DOOR 2
#define PASSAGE 5

#define DOOR_CLOSED 2
#define PASSAGE_CLOSED 5

#define SLIDER_OPENED 0
#define SLIDER_OPENING 3
#define SLIDER_CLOSING 4

#define MOVING_DOOR_TIME 1000
#define TIME_BEFORE_CLOSING_DOOR 10000

#define MOVING_PASSAGE_TIME 3000
#define TIME_BEFORE_CLOSING_PASSAGE 10000

#define TEX_WIDTH 64
#define TEX_HEIGHT 64
#define SHADE_TEX 128
#define ORIGINAL_TEX 255

#endif //GAMECONSTANTS_H
