#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

#define DOOR_OPENED 0
#define DOOR_CLOSED 2
#define DOOR_OPENING 3
#define DOOR_CLOSING 4

#define MOVING_DOOR_TIME 1000
#define TIME_BEFORE_CLOSING_DOOR 10000

#endif //GAMECONSTANTS_H
