#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

#define WALL 1

#define LOCKED_DOOR 10
#define PASSAGE 11
#define AUTOMATIC_DOOR 12

#define SLIDER_OPENED 0
#define SLIDER_OPENING 1
#define SLIDER_CLOSING 2

#define MOVING_DOOR_TIME 1000
#define TIME_BEFORE_CLOSING_DOOR 10000

#define MOVING_PASSAGE_TIME 3000
#define TIME_BEFORE_CLOSING_PASSAGE 10000

#define MOVING_AUTO_DOOR_TIME 1000
#define TIME_BEFORE_CLOSING_AUTO_DOOR 10000

#define TEX_WIDTH 64
#define TEX_HEIGHT 64
#define SHADE_TEX 128
#define ORIGINAL_TEX 255

#define LEADERBOARD_ELEMENTS 15
#define LEADERBOARD_SLEEP_TIME_1 800000
#define LEADERBOARD_SLEEP_TIME_2 550000

#define LIVES_HUD 0
#define HP_HUD 1
#define WEAPON_HUD 2
#define KEY_HUD 3
#define FIRING_HUD 4
#define AMMO_HUD 5
#define SCORE_HUD 6

#define DEATH_TIME 400

#endif //GAMECONSTANTS_H
